### ISSUE TITLE
GL.iNet GL-B1300 Support

### ISSUE THREAD

**Issue by the4anoni** [NoTengoBattery/openwrt#13]
Hi

What is current state of support for GL.iNet GL-B1300?
I really need this build, as I am using VLAN on WAN to establish PPPoE sessios with my ISP.

**Comment by NoTengoBattery** [comment]
Hello! The device should technically work (at least it should boot) but I have not tested. I have no device to test it or a tester willing to do it at the moment. So the current status should be "untested".

**Comment by the4anoni** [comment]
> Hello! The device should technically work (at least it should boot) but I have not tested. I have no device to test it or a tester willing to do it at the moment. So the current status should be "untested".

Before testing what partitions should I backup? Maybe when I will have free time I could test (that won't be soon through...).

**Comment by NoTengoBattery** [comment]
Excellent, I'll be waiting to hear about it!

**Comment by the4anoni** [comment]
@NoTengoBattery Hi
I am back from Hospital and now I have time to test.

EDIT: I did backup of all partitions, then flashed your build. Router doesn't boot anymore. Now I am restoring it via U-Boot.

EDIT1: Restored via uboot successfully.

**Comment by NoTengoBattery** [comment]
@the4anoni, sorry for the late reply. Yes, I expect it to not boot at the moment. I need more debugging information before making a bootable image. Maybe we can start there! Note that I'm rather busy with my studies now, so I've been waiting for the 20.04 or 21.xx releases, but they don't seem to release somewhere near. My idea is to provide a final stable version based on their stable version. Sadly, the 19.xx series does not have a Linux kernel 5.4 or newer (required for most fixes).

Edit: I forgot to say, it is good that you're okay and no longer in the hospital :]
